"""create transcript chunks

Revision ID: 1cb7f58f6ad0
Revises: 8753cf7d4f4f
Create Date: 2026-08-01 20:59:57.336173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '1cb7f58f6ad0'
down_revision: Union[str, Sequence[str], None] = '8753cf7d4f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.String(), nullable=False),
    sa.Column('guest', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('youtube_url', sa.String(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_chunks_episode'), 'transcript_chunks', ['episode'], unique=False)
    op.create_index(op.f('ix_transcript_chunks_guest'), 'transcript_chunks', ['guest'], unique=False)
    op.create_index(op.f('ix_transcript_chunks_id'), 'transcript_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_chunks_id'), table_name='transcript_chunks')
    op.drop_index(op.f('ix_transcript_chunks_guest'), table_name='transcript_chunks')
    op.drop_index(op.f('ix_transcript_chunks_episode'), table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    # ### end Alembic commands ###
