"""Update Workspace Model

Revision ID: 261581aed4f4
Revises: 32a103b692fd
Create Date: 2026-07-30 22:25:10.520011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261581aed4f4'
down_revision: Union[str, Sequence[str], None] = '32a103b692fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('icon', sa.String(length=20), nullable=False))
    op.add_column('workspaces', sa.Column('color', sa.String(length=30), nullable=False))
    op.add_column('workspaces', sa.Column('default_model', sa.String(length=100), nullable=False))
    op.add_column('workspaces', sa.Column('mode', sa.String(length=50), nullable=False))
    op.add_column('workspaces', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'created_at')
    op.drop_column('workspaces', 'mode')
    op.drop_column('workspaces', 'default_model')
    op.drop_column('workspaces', 'color')
    op.drop_column('workspaces', 'icon')
    # ### end Alembic commands ###
